---
- connection: local
  hosts: localhost
  tasks:
  - lineinfile:
      create: 'yes'
      dest: uuids.csv
      insertbefore: BOF
      line: '"Resource Type","Resource Name","Old","New"'
      regexp: '"Resource Type","Resource Name","Old","New"'
      state: present
    name: Initializing UUID mapping file
  - name: Add public key downpour-demo
    os_keypair:
      name: downpour-demo
      public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD1kLlTkB6VCdXxsolsXPo00XqcX0boWXubqvrtPdn99RxvR4FdmQZNBl6v4OAUkZUG0EntAjRFFH3v97ea6TZNRobLMTJkP73RjHcsieu3JN4P3vdTz6NrHGY7wweuStBa6bSxFctxPjrKBrjICY2wq/x5Kjjc4pLEq/a8qa7ygwym2bvtDoOFJAmz5ec1AyOllcVOM9HffMogTQJNG6/37dQZJ0KbERCDCC5YVsOOPoTXa/EHaAVRyX5ivEDsPNCf0sWqz8JRMekNfEao2BkJwiG+ia/OEXO1aUukp2gRFDi8fapESBlBHefxt+Cqbsqyj1niobn0EGfINo3BVnZ7
        Generated-by-Nova
    register: key001
  - lineinfile:
      dest: uuids.csv
      insertafter: EOF
      line: '"keypair","downpour-demo","downpour-demo","{{key001.key.id}}"'
      regexp: '"keypair","downpour-demo","downpour-demo"'
      state: present
    name: Map UUID for keypair downpour-demo
  - name: Add security group downpour-demo
    os_security_group:
      description: Demo group used for downpour
      name: downpour-demo
      state: present
    register: sg002
  - lineinfile:
      dest: uuids.csv
      insertafter: EOF
      line: '"security group","downpour-demo","3c7dcb77-d9ac-4af1-ba95-3f5d89a85227","{{sg002.secgroup.id}}"'
      regexp: '"security group","downpour-demo","3c7dcb77-d9ac-4af1-ba95-3f5d89a85227"'
      state: present
    name: Map UUID for security group downpour-demo
  - name: Add rule to security group downpour-demo
    os_security_group_rule:
      direction: ingress
      ethertype: IPv4
      port_range_max: 443
      port_range_min: 443
      protocol: tcp
      security_group: downpour-demo
      state: present
  - name: Add rule to security group downpour-demo
    os_security_group_rule:
      direction: egress
      ethertype: IPv6
      protocol: null
      security_group: downpour-demo
      state: present
  - name: Add rule to security group downpour-demo
    os_security_group_rule:
      direction: egress
      ethertype: IPv4
      protocol: null
      security_group: downpour-demo
      state: present
  - name: Add rule to security group downpour-demo
    os_security_group_rule:
      direction: ingress
      ethertype: IPv4
      port_range_max: 22
      port_range_min: 22
      protocol: tcp
      security_group: downpour-demo
      state: present
  - name: Create network private
    os_network:
      external: false
      name: private
      shared: false
      state: present
    register: net003
  - lineinfile:
      dest: uuids.csv
      insertafter: EOF
      line: '"network","private","56a86bdb-13b2-4c9f-b8f5-a942d52602b5","{{net003.network.id}}"'
      regexp: '"network","private","56a86bdb-13b2-4c9f-b8f5-a942d52602b5"'
      state: present
    name: Map UUID for network private
  - name: Create subnet private-subnet on network private
    os_subnet:
      allocation_pool_end: 10.0.0.62
      allocation_pool_start: 10.0.0.2
      cidr: 10.0.0.0/26
      dns_nameservers: []
      gateway_ip: 10.0.0.1
      ip_version: 4
      name: private-subnet
      network_name: private
      state: present
    register: subnet004
  - lineinfile:
      dest: uuids.csv
      insertafter: EOF
      line: '"subnet","private-subnet","e6baf9f4-09b5-4292-8236-3cca609ec2a3","{{subnet004.subnet.id}}"'
      regexp: '"subnet","private-subnet","e6baf9f4-09b5-4292-8236-3cca609ec2a3"'
      state: present
    name: Map UUID for subnet private-subnet
  - name: Create subnet ipv6-private-subnet on network private
    os_subnet:
      allocation_pool_end: fd62:49da:46e2:0:ffff:ffff:ffff:ffff
      allocation_pool_start: fd62:49da:46e2::2
      cidr: fd62:49da:46e2::/64
      dns_nameservers: []
      gateway_ip: fd62:49da:46e2::1
      ip_version: 6
      ipv6_address_mode: slaac
      ipv6_ra_mode: slaac
      name: ipv6-private-subnet
      network_name: private
      state: present
    register: subnet005
  - lineinfile:
      dest: uuids.csv
      insertafter: EOF
      line: '"subnet","ipv6-private-subnet","8d736fe4-6b8f-4bf5-a38e-b511dce21f7f","{{subnet005.subnet.id}}"'
      regexp: '"subnet","ipv6-private-subnet","8d736fe4-6b8f-4bf5-a38e-b511dce21f7f"'
      state: present
    name: Map UUID for subnet ipv6-private-subnet
  - name: Creating image xenial-server-cloudimg-amd64-disk1
    os_image:
      container_format: bare
      disk_format: qcow2
      filename: xenial-server-cloudimg-amd64-disk1.dat
      min_disk: 0
      min_ram: 0
      name: xenial-server-cloudimg-amd64-disk1
    register: img006
  - lineinfile:
      dest: uuids.csv
      insertafter: EOF
      line: '"image","xenial-server-cloudimg-amd64-disk1","1b5405bb-5f99-43ae-b0b0-be43952ab891","{{img006.image.id}}"'
      regexp: '"image","xenial-server-cloudimg-amd64-disk1","1b5405bb-5f99-43ae-b0b0-be43952ab891"'
      state: present
    name: Map UUID for image xenial-server-cloudimg-amd64-disk1
  - name: Creating server downpour-demo-tiny
    os_server:
      image: xenial-server-cloudimg-amd64-disk1
      key_name: downpour-demo
      name: downpour-demo-tiny
      nics:
      - private
      state: present
    register: server007
  - lineinfile:
      dest: uuids.csv
      insertafter: EOF
      line: '"server","downpour-demo-tiny","94522ab4-1803-4452-8022-75b35c5c956e","{{server007.server.id}}"'
      regexp: '"server","downpour-demo-tiny","94522ab4-1803-4452-8022-75b35c5c956e"'
      state: present
    name: Map UUID for server downpour-demo-tiny